### ISSUE TITLE
Oper support?

### ISSUE THREAD

**Issue by liothen** [mkroman/blur#8]
Are there any plans to include an oper command? Maybe even one that's bound to network in the config?

I tried just adding the oper lines in the ```on :connection_ready``` block but the oper.motd keeps triggering the block over and over again.

if you did something similar to how you cycle though networks, you could provide oper support for other networks as well

i.e.
``` yaml
- &uplink
  <<: *defaults
  hostname: irc.uplink.io
  nickname: basic-example
  secure: true
  port: 6697
  oper:
    username: this
    password: pass
  channels:
  - "#channel1"
  - "#channel2"
```

I am working on a dnsbl/dronebl using your framework which seems almost ideal setup

**Comment by mkroman** [comment]
I don't think adding the oper command to the framework is necessary, since the need for it might be limited.

A better approach would be to write a simple oper script that uses script-specific variables and sends the `OPER` command once the network emits the `:network_ready` event, given that there's oper credentials for the network.

The end-result will be much like your example.

**Comment by mkroman** [comment]
I just fixed passing of script variables with commit 4fc8d647752685b6e6e7ef72d5ed103116ccdbe0.

A script to achieve this could look like this:
```ruby
Script :oper do
  Author '…'
  Version '0.1'
  Description 'Automatically sends OPER commands to supported networks.'

  client.on :connection_ready do |network|
    if credentials = config[network.host]
      network.transmit :OPER, credentials['username'], credentials['password']
    end
  end
end
```

And then to specify credentials you could have this in your config.yml:
```yaml
scripts:
  oper:
    'irc.uplink.io':
      username: 'user'
      password: 'pass'
```

Or, if you really prefer to have the oper credentials in the network block, you could replace the conditional as such:
```ruby
    if credentials = network.options['oper']
      network.transmit :OPER, credentials['user'], credentials['pass']
    end
```

And the configuration will be like in your example.
